name: CI/CD Pipeline with ServiceNow Change

on:
  push:
    branches:
      - main

jobs:

  plan:
    name: Plan
    runs-on: ubuntu-latest
    steps:
      - name: Planning stage
        run: |
          echo "📋 Planning deployment..."
          echo "Checking scope, impact, dependencies"
          sleep 1
          echo "✅ Plan completed"

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: plan
    steps:
      - name: Build stage
        run: |
          echo "🏗️ Building application..."
          sleep 1
          echo "✅ Build successful"

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test stage
        run: |
          echo "🧪 Running tests..."
          sleep 1
          echo "✅ Tests passed"

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: ServiceNow DevOps Change (Async)
        uses: ServiceNow/servicenow-devops-change@main
        with:
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
          job-name: Deploy to Production
          context-github: ${{ toJson(github) }}
          change-request: '{"setCloseCode":"true",
            "attributes":
              {
                "short_description":"Automated Software Deployment",
                "requested_by":"bae8cbe1936a32100e5c79befaba10f1"}
              }'
          # 🔑 Async / Non-blocking
          abortOnChangeCreationFailure: true
          abortOnChangeStepTimeout: false
          changeCreationTimeout: 10

      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Get commit message
        run:  |
              echo "Commit message is ${{ github.event.head_commit.message }}"
              echo "Repository name (owner/repo): ${{ github.repository }}"
              echo "Repository owner: ${{ github.repository_owner }}"
              echo "Repository name only: ${{ github.event.repository.name }}"
              echo "Branch/Tag ref: ${{ github.ref }}"
              echo "Commit SHA: ${{ github.sha }}"
              echo "Workflow triggered by: ${{ github.actor }}"
              echo "Workspace directory: ${{ github.workspace }}"
              echo "Event name: ${{ github.event_name }}"
      
              # Accessing via environment variables
              echo "Repository via env var: $GITHUB_REPOSITORY"
              echo "Commit SHA via env var: $GITHUB_SHA"

      - name: Simulate deployment
        run: |
          echo "🚀 Deploying application..."
          sleep 2
          echo "✅ Deployment completed"

      
